run:
  timeout: 3m

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck

linters-settings:
  errcheck:
    exclude-functions:
      - (io.Closer).Close
      - os.Remove
      - os.Setenv
      - os.Unsetenv
      - (net/http.ResponseWriter).Write
      - (*encoding/json.Encoder).Encode

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
